import {
  Anchor,
  Armchair,
  Baby,
  Backpack,
  Banknote,
  Beef,
  Beer,
  Bike,
  Bone,
  Book,
  Briefcase,
  Brush,
  Bus,
  Cake,
  Camera,
  CandyCane,
  Car,
  CarFront,
  Church,
  Cigarette,
  Clapperboard,
  Coffee,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Dog,
  Drama,
  Droplets,
  Dumbbell,
  Egg,
  Fish,
  Flame,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GlassWater,
  Glasses,
  GraduationCap,
  Guitar,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  Home,
  Hospital,
  Hotel,
  IceCream,
  Key,
  Lamp,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  type LucideIcon,
  Martini,
  Medal,
  Milk,
  Mountain,
  Music,
  Newspaper,
  PaintRoller,
  Palette,
  ParkingMeter,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Printer,
  Recycle,
  Rocket,
  Salad,
  Sandwich,
  Scissors,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Stethoscope,
  Sun,
  Syringe,
  Ticket,
  Train,
  TramFront,
  Trees,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  WashingMachine,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react';

// Bibliotheque large mais bornee : couvrir les depenses d'un foyer sans
// transformer le choix en catalogue interminable.
export const CUSTOM_ICONS: Record<string, LucideIcon> = {
  Utensils, Pizza, Sandwich, Salad, Beef, Fish, Egg, Milk, Croissant, Cake,
  IceCream, CandyCane, Popcorn, Coffee, GlassWater, Wine, Beer, Martini,
  ShoppingCart, ShoppingBag, Gift, Shirt, Watch, Glasses, Gem, Backpack,
  Scissors, Sparkles, Brush, Palette,
  Home, Sofa, Armchair, Lamp, Key, Hammer, Wrench, Shovel, PaintRoller,
  WashingMachine, Tv, Laptop, Cpu, Printer, Smartphone, Phone, Wifi, Plug,
  Lightbulb, Zap, Droplets, Flame, Snowflake, Recycle,
  Banknote, CreditCard, Wallet, PiggyBank, Briefcase, Newspaper,
  Car, CarFront, Fuel, ParkingMeter, Bus, Train, TramFront, Bike, Plane, Ship,
  Anchor, Truck, Luggage, Hotel, Ticket, Mountain,
  Heart, HandHeart, Stethoscope, Hospital, Pill, Syringe, Cross,
  Baby, Dog, PawPrint, Bone, GraduationCap, Book, Church,
  Gamepad2, Music, Guitar, Headphones, Camera, Clapperboard, Drama, Trophy,
  Medal, Dumbbell, Rocket,
  Sun, Umbrella, Leaf, Trees, TreePine, Flower2, Waves, Cigarette,
};

export const CUSTOM_COLORS = [
  'oklch(0.72 0.17 30)',
  'oklch(0.72 0.17 55)',
  'oklch(0.78 0.16 80)',
  'oklch(0.8 0.16 100)',
  'oklch(0.78 0.17 130)',
  'oklch(0.68 0.15 155)',
  'oklch(0.72 0.13 175)',
  'oklch(0.75 0.15 195)',
  'oklch(0.72 0.14 215)',
  'oklch(0.72 0.15 240)',
  'oklch(0.65 0.18 265)',
  'oklch(0.62 0.19 285)',
  'oklch(0.68 0.19 320)',
  'oklch(0.7 0.19 345)',
  'oklch(0.7 0.17 15)',
  'oklch(0.58 0.14 40)',
  'oklch(0.55 0.1 150)',
  'oklch(0.52 0.12 250)',
  'oklch(0.8 0.04 260)',
  'oklch(0.65 0.03 260)',
];

export const customIcon = (name?: string): LucideIcon | undefined =>
  name ? CUSTOM_ICONS[name] : undefined;
